version: "3.8"

services:

  consul:
    image: hashicorp/consul:1.16
    container_name: consul
    command: "agent -dev -client=0.0.0.0"
    ports:
      - "8500:8500"

  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_DB: medical_history
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"